server:
  servlet:
    context-path: /
  port: 3366
spring:
  application:
    name: microservices-banking-cloud-gateway-api-project
  profiles:
    active: default
  cloud:
    config:
      fail-fast: false
      retry:
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.6
        max-attempts: 6
    gateway:
      routes:
      - id: microservices-banking-accounts-service-project
        uri: lb://microservices-banking-accounts-service-project
        predicates:
        - Path=/api/accounts/**
      - id: microservices-banking-cards-service-project
        uri: lb://microservices-banking-cards-service-project
        predicates:
        - Path=/api/cards/**
      - id: microservices-banking-loans-service-project
        uri: lb://microservices-banking-loans-service-project
        predicates:
        - Path=/api/loans/**
  config:
    import: optional:configserver:http://localhost:9924
    activate:
      on-profile: default
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:1030/realms/microservices_master_realm/protocol/openid-connect/certs
management:
    tracing:
        sampling:
            probability: 1.0