server:
  port: 8761

spring:
  application:
    name: microservices-banking-eureka-server-project

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
management:
  tracing:
    sampling:
      probability: 1.0