server:
  port: 9924
spring:
  application:
    name: microservices-banking-configuration-server-project
  cloud:
    config:
      enabled: false
      server:
        git:
          clone-on-start: true
          default-label: master
          uri: https://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@github.com/KirtiShekhar/DockerK8sBankingApplicationsConfigServer.git
          username: KirtiShekhar
          password:  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
          timeout: 60
  profiles:
    active: git
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*" 
  tracing:
    sampling:
      probability: 1.0