apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-configmap
  labels:
    app: config-map
data:
  SPRING_CONFIG_IMPORT: "configserver:http://config-server-service:9924/"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-service-registry-configmap
  labels:
    app: config-map
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-service-registry-0.eureka-service-registry:8761/eureka-service-registry"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  labels:
    app: config-map
data:
  HOSTNAME: "mysql-0.mysql"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-configmap
  labels:
    app: config-map
data:
  init.sql: |
    CREATE DATABASE IF NOT EXIST microservicesdockercontainerkubernetes;
    USE microservicesdockercontainerkubernetes;

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zipkin-tracing-endpoint-configmap
  labels:
    app: config-map
data:
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin-service:9411/api/v2/spans

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-profile-active-configmap
  labels:
    app: config-map
data:
  SPRING_PROFILE_ACTIVE: default

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config-profile-active-configmap
  labels:
    app: config-map
data:
  SPRING_CONFIG_PROFILE_ACTIVE: git

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-eureka-server-application-name-configmap
  labels:
    app: config-map
data:
  BANKING_EUREKA_SERVER_APPLICATION_NAME: microservices-banking-eureka-server-project

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-configuration-server-application-name-configmap
  labels:
    app: config-map
data:
  BANKING_CONFIGURATION_SERVER_APPLICATION_NAME: microservices-banking-configuration-server-project

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-accounts-service-application-name-configmap
  labels:
    app: config-map
data:
  BANKING_ACCOUNTS_SERVICE_APPLICATION_NAME: microservices-banking-accounts-service-project

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-cards-service-application-name-configmap
  labels:
    app: config-map
data:
  BANKING_CARDS_SERVICE_APPLICATION_NAME: microservices-banking-cards-service-project

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-loans-service-application-name-configmap
  labels:
    app: config-map
data:
  BANKING_LOANS_SERVICE_APPLICATION_NAME: microservices-banking-loans-service-project

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-cloud-gateway-api-application-name-configmap
  labels:
    app: config-map
data:
  BANKING_CLOUD_GATEWAY_API_APPLICATION_NAME: microservices-banking-cloud-gateway-api-project
